### ISSUE TITLE
Why do I compile SharpMap.UI, always go wrong, do you have it, using the latest source code

### ISSUE THREAD

**Issue by caiyusheng** [SharpMap/SharpMap#80] opened 2018-03-14 02:15 UTC
Why do I compile SharpMap.UI, always go wrong, do you have it, using the latest source code

**Comment by caiyusheng** [comment] 2018-03-14 08:34
internal bool Draggint
        {

            get => _dragging;
        }

 "get => "   wrong

**Comment by FObermaier** [comment] 2018-03-14 10:39
You are probably not using VS2017. This is a C# language feature that requires this VS version.

**Comment by am2222** [comment] 2018-03-14 12:15
Using VS 2017 and last version which is available in `sharpmap's repository` I could compile it without any problems,It seems the problem is with your VS version

**Comment by caiyusheng** [comment] 2018-03-14 15:45
I use this version of VS2015, this version is the failure to compile, I change the VS2017 try

**Comment by joriswit** [comment] 2018-03-14 17:23
This also seems to be the cause of TeamCity's build failure. Can TeamCity be configured to use the VS2017 build tools?

**Comment by joriswit** [comment] 2018-03-21 19:37
Closing issue, as @caiyusheng has updated to VS2017, and TeamCity build works again.

**Closed as completed by joriswit** 2018-03-21 19:37 UTC
